package _3_nullability

fun fail(message: String) = throw AssertionError(message)